[profile.default]
solc_version = "0.8.18"
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 3000
verbosity = 1
src = "src"
test = "test"
out = "out"
allow_paths = ["../../node_modules", "../../../../packages"]
extra_output_files = [
  "abi",
  "evm.bytecode"
]
fs_permissions = [{ access = "read", path = "./"}]
gas_price = 0
block_base_fee_per_gas = 0
[profile.lattice-testnet]
eth_rpc_url = "https://follower.testnet-chain.linfra.xyz"
[profile.sepolia]
eth_rpc_url = "https://sepolia.infura.io/v3/724355a95cff43869434401fd2c7c17d"